(() => {
  const locale = (document.documentElement.lang || "ru").slice(0, 2);
  const copy = {
    ru: { title: "Космические места рядом.", lead: "Найдите планетарии, обсерватории и научные центры вокруг себя. Список формируется из открытых геоданных после вашего согласия на геолокацию.", action: "Найти рядом со мной", solar: "Солнечная система", radiusLabel: "Радиус поиска", live: "открытые данные", waiting: "Ожидаем геолокацию", privacy: "Координаты используются только для текущего поиска и не сохраняются.", placesLabel: "объектов", resultsTitle: "Астрономия на карте.", resultsNote: "Нажмите «Найти рядом со мной», чтобы выполнить поиск в радиусе 100 км.", mapWaiting: "Карта и места появятся после разрешения геолокации.", emptyTitle: "Ваш маршрут к небу.", emptyText: "Мы покажем только реальные объекты, найденные в открытых картографических данных.", howTitle: "Откройте точку наблюдения.", stepOneTitle: "Разрешите поиск", stepOneText: "Браузер запрашивает вашу текущую геопозицию только по нажатию кнопки.", stepTwoTitle: "Сравните места", stepTwoText: "Планетарии, обсерватории, музеи науки и образовательные центры появляются на карте.", stepThreeTitle: "Откройте маршрут", stepThreeText: "Каждая карточка ведёт к объекту в OpenStreetMap для самостоятельного построения пути.", searching: "Ищем реальные места поблизости…", found: "Найдено", none: "Подходящие места не найдены в заданном радиусе.", denied: "Геолокация недоступна. Разрешите её в браузере и повторите поиск.", failed: "Открытые карты временно недоступны. Попробуйте позже.", type: "Тип", open: "Открыть в OpenStreetMap ↗" },
    en: { title: "Space places nearby.", lead: "Find nearby planetariums, observatories and science centres. The live list is built from open map data after you approve location access.", action: "Find places near me", solar: "Solar system", radiusLabel: "Search radius", live: "open data", waiting: "Awaiting location", privacy: "Coordinates are used only for this search and are not stored.", placesLabel: "places", resultsTitle: "Astronomy on the map.", resultsNote: "Use the button to search within 100 km of your current location.", mapWaiting: "The map and places will appear after location access is allowed.", emptyTitle: "Your path to the sky.", emptyText: "Only real venues found in open map data will be shown.", howTitle: "Find a place to observe.", stepOneTitle: "Allow search", stepOneText: "Your browser requests a location only after you use the button.", stepTwoTitle: "Compare places", stepTwoText: "Planetariums, observatories, science museums and education centres appear on the map.", stepThreeTitle: "Open the route", stepThreeText: "Every card opens the venue in OpenStreetMap so you can plan the journey yourself.", searching: "Searching real places nearby…", found: "Found", none: "No suitable places were found in this radius.", denied: "Location is unavailable. Allow it in your browser and try again.", failed: "Open maps are temporarily unavailable. Please try again later.", type: "Type", open: "Open in OpenStreetMap ↗" },
    tr: { title: "Yakındaki uzay yerleri.", lead: "Yakınınızdaki gezegenevlerini, gözlemevlerini ve bilim merkezlerini bulun. Canlı liste, konum izninizden sonra açık harita verilerinden oluşturulur.", action: "Yakınımdaki yerleri bul", solar: "Güneş sistemi", radiusLabel: "Arama yarıçapı", live: "açık veri", waiting: "Konum bekleniyor", privacy: "Koordinatlar yalnızca bu arama için kullanılır, kaydedilmez.", placesLabel: "yer", resultsTitle: "Haritada astronomi.", resultsNote: "Geçerli konumunuzun 100 km çevresinde aramak için düğmeyi kullanın.", mapWaiting: "Konum izni verildiğinde harita ve yerler görünür.", emptyTitle: "Gökyüzüne giden rotanız.", emptyText: "Yalnızca açık harita verilerinde bulunan gerçek yerler gösterilir.", howTitle: "Gözlem noktası bulun.", stepOneTitle: "Aramaya izin verin", stepOneText: "Tarayıcınız konumu yalnızca düğmeye bastığınızda ister.", stepTwoTitle: "Yerleri karşılaştırın", stepTwoText: "Gezegenevleri, gözlemevleri, bilim müzeleri ve eğitim merkezleri haritada görünür.", stepThreeTitle: "Rotayı açın", stepThreeText: "Her kart, yolculuğu kendiniz planlayabilmeniz için yeri OpenStreetMap'te açar.", searching: "Yakındaki gerçek yerler aranıyor…", found: "Bulundu", none: "Bu yarıçapta uygun yer bulunamadı.", denied: "Konum kullanılamıyor. Tarayıcıda izin verip tekrar deneyin.", failed: "Açık haritalar geçici olarak kullanılamıyor. Lütfen daha sonra tekrar deneyin.", type: "Tür", open: "OpenStreetMap'te aç ↗" }
  };
  const t = copy[locale] || copy.ru;
  const set = (selector, value) => document.querySelectorAll(selector).forEach(node => { node.textContent = value; });
  document.querySelectorAll("[data-place-copy]").forEach(node => { const value = t[node.dataset.placeCopy]; if (value) node.textContent = value; });
  const button = document.getElementById("findPlaces"), results = document.getElementById("placesResults"), status = document.getElementById("placeStatus"), locationLabel = document.getElementById("placeLocation"), count = document.getElementById("placeCount");
  let map, layer;
  const escape = value => String(value || "").replace(/[&<>'"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char]);
  const mapUrl = (lat, lon) => `https://www.openstreetmap.org/?mlat=${lat}&mlon=${lon}#map=16/${lat}/${lon}`;
  function showMessage(title, text) { results.innerHTML = `<div class="oa-place-empty"><strong>${escape(title)}</strong><p>${escape(text)}</p></div>`; }
  function setupMap(lat, lon) { if (!window.L) return; if (!map) { map = L.map("placesMap", { scrollWheelZoom: false }).setView([lat, lon], 10); L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", { maxZoom: 19, attribution: "© OpenStreetMap contributors" }).addTo(map); } else map.setView([lat, lon], 10); if (layer) layer.clearLayers(); layer = L.layerGroup().addTo(map); L.circleMarker([lat, lon], { radius: 8, color: "#ecfeff", weight: 2, fillColor: "#42d5e8", fillOpacity: 1 }).addTo(layer).bindPopup(t.waiting); }
  async function search(lat, lon) { const query = `[out:json][timeout:25];(nwr["amenity"="planetarium"](around:100000,${lat},${lon});nwr["man_made"="observatory"](around:100000,${lat},${lon});nwr["tourism"="museum"]["museum"="science"](around:100000,${lat},${lon});nwr["amenity"="science_centre"](around:100000,${lat},${lon}););out center tags 30;`; const response = await fetch(`https://overpass-api.de/api/interpreter?data=${encodeURIComponent(query)}`, { headers: { Accept: "application/json" } }); if (!response.ok) throw new Error(`Overpass ${response.status}`); return (await response.json()).elements || []; }
  function render(places) { count.textContent = String(places.length); status.textContent = places.length ? `${t.found}: ${places.length}` : t.none; if (!places.length) return showMessage(t.none, t.resultsNote); results.innerHTML = places.map(place => { const tags = place.tags || {}, lat = place.lat ?? place.center?.lat, lon = place.lon ?? place.center?.lon, type = tags.amenity || tags.man_made || tags.tourism || "place"; const name = tags.name || tags["name:en"] || t.type; return `<article class="oa-place-card"><div><small>${escape(t.type)} · ${escape(type.replace(/_/g, " "))}</small><h3>${escape(name)}</h3><p>${escape([tags["addr:street"], tags["addr:city"]].filter(Boolean).join(", ") || "OpenStreetMap")}</p></div>${Number.isFinite(lat) && Number.isFinite(lon) ? `<a href="${mapUrl(lat, lon)}" target="_blank" rel="noopener noreferrer">${escape(t.open)}</a>` : ""}</article>`; }).join(""); places.forEach(place => { const lat = place.lat ?? place.center?.lat, lon = place.lon ?? place.center?.lon; if (!Number.isFinite(lat) || !Number.isFinite(lon) || !layer) return; const tags = place.tags || {}; L.circleMarker([lat, lon], { radius: 7, color: "#ecfeff", weight: 1, fillColor: "#ffc162", fillOpacity: .94 }).addTo(layer).bindPopup(escape(tags.name || tags["name:en"] || t.type)); }); }
  button?.addEventListener("click", () => { if (!navigator.geolocation) { status.textContent = t.denied; return; } button.disabled = true; status.textContent = t.searching; navigator.geolocation.getCurrentPosition(async position => { const { latitude: lat, longitude: lon } = position.coords; locationLabel.textContent = `${lat.toFixed(3)}°, ${lon.toFixed(3)}°`; setupMap(lat, lon); try { render(await search(lat, lon)); } catch { status.textContent = t.failed; showMessage(t.failed, t.resultsNote); } finally { button.disabled = false; } }, () => { status.textContent = t.denied; button.disabled = false; }); });
})();
