(() => {
  const root = document.getElementById("worldAtlas"); if (!root) return;
  const locale = (document.documentElement.lang || "ru").slice(0, 2).toLowerCase();
  const apiBase = (window.ORBITAL_ATLAS_API || "https://albaspace-api.nncdecdgc.workers.dev").replace(/\/$/, "");
  const copy = {
    ru: { loading: "Загружаем утверждённую номенклатуру USGS…", unavailable: "Номенклатура временно недоступна. Попробуйте обновить страницу позже.", mars: "Марс", moon: "Луна", count: "объектов", visible: "на карте", search: "Найти объект: например, Olympus или Tycho", all: "Все типы", crater: "Кратеры", mons: "Горы", vallis: "Долины", plain: "Равнины", other: "Остальные", select: "Выберите точку на карте или объект из списка.", feature: "объект IAU", type: "Тип", diameter: "Диаметр", coordinates: "Координаты", approval: "Утверждён", quad: "Квадрангл", origin: "Происхождение названия", source: "ОТКРЫТЬ КАРТОЧКУ USGS ↗", noResults: "Нет объектов, соответствующих текущему поиску и слоям.", share: "СКОПИРОВАТЬ ССЫЛКУ", copied: "ССЫЛКА СКОПИРОВАНА", updated: "Снимок USGS", sourceLabel: "Официальный источник" },
    en: { loading: "Loading approved USGS nomenclature…", unavailable: "Nomenclature is temporarily unavailable. Please refresh the page later.", mars: "Mars", moon: "Moon", count: "features", visible: "on map", search: "Find a feature: for example, Olympus or Tycho", all: "All types", crater: "Craters", mons: "Mountains", vallis: "Valleys", plain: "Plains", other: "Other", select: "Choose a point on the map or a feature from the list.", feature: "IAU feature", type: "Type", diameter: "Diameter", coordinates: "Coordinates", approval: "Approved", quad: "Quadrangle", origin: "Name origin", source: "OPEN USGS FEATURE ↗", noResults: "No features match the current search and layers.", share: "COPY LINK", copied: "LINK COPIED", updated: "USGS snapshot", sourceLabel: "Official source" },
    tr: { loading: "USGS onaylı adlandırmaları yükleniyor…", unavailable: "Adlandırma geçici olarak kullanılamıyor. Lütfen sayfayı daha sonra yenileyin.", mars: "Mars", moon: "Ay", count: "nesne", visible: "haritada", search: "Bir nesne bulun: örneğin Olympus veya Tycho", all: "Tüm türler", crater: "Kraterler", mons: "Dağlar", vallis: "Vadiler", plain: "Ovalar", other: "Diğer", select: "Haritada bir nokta veya listeden bir nesne seçin.", feature: "IAU nesnesi", type: "Tür", diameter: "Çap", coordinates: "Koordinatlar", approval: "Onay", quad: "Karesi", origin: "Adın kökeni", source: "USGS KARTINI AÇ ↗", noResults: "Mevcut arama ve katmanlara uygun nesne yok.", share: "BAĞLANTIYI KOPYALA", copied: "BAĞLANTI KOPYALANDI", updated: "USGS görüntüsü", sourceLabel: "Resmî kaynak" }
  };
  const t = copy[locale] || copy.ru; const labels = { mars: t.mars, moon: t.moon }; const endpoints = { mars: "mars", moon: "moon" };
  const initial = new URL(location.href).searchParams.get("body");
  const state = { body: endpoints[initial] ? initial : "mars", data: null, selectedId: new URL(location.href).searchParams.get("feature") || "", query: "", active: new Set(["AA", "MO", "VA", "PL", "other"]) };
  const groups = [["AA", "crater"], ["MO", "mons"], ["VA", "vallis"], ["PL", "plain"], ["other", "other"]];
  const groupFor = feature => ["AA", "MO", "VA", "PL"].includes(feature.code) ? feature.code : "other";
  const nf = new Intl.NumberFormat(locale === "ru" ? "ru-RU" : locale === "tr" ? "tr-TR" : "en-US", { maximumFractionDigits: 1 });
  const df = new Intl.DateTimeFormat(locale === "ru" ? "ru-RU" : locale === "tr" ? "tr-TR" : "en-US", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit", timeZone: "UTC", timeZoneName: "short" });
  const el = id => document.getElementById(id); const make = (tag, opts = {}) => { const node = document.createElement(tag); if (opts.className) node.className = opts.className; if (opts.text !== undefined) node.textContent = String(opts.text); if (opts.type) node.type = opts.type; return node; };
  const safeUrl = value => { try { const url = new URL(value); return url.protocol === "https:" && url.hostname === "planetarynames.wr.usgs.gov" ? url.href : "https://planetarynames.wr.usgs.gov/"; } catch { return "https://planetarynames.wr.usgs.gov/"; } };
  const visible = () => { const q = state.query.trim().toLocaleLowerCase(); return (state.data?.features || []).filter(feature => state.active.has(groupFor(feature)) && (!q || `${feature.name} ${feature.cleanName || ""} ${feature.type || ""} ${feature.origin || ""}`.toLocaleLowerCase().includes(q))); };
  function syncUrl() { const url = new URL(location.href); url.searchParams.set("body", state.body); state.selectedId ? url.searchParams.set("feature", state.selectedId) : url.searchParams.delete("feature"); history.replaceState({}, "", url); }
  function select(id) { state.selectedId = state.data?.features.some(f => f.id === id) ? id : ""; syncUrl(); render(); el("worldDetail")?.scrollIntoView({ behavior: "smooth", block: "nearest" }); }
  function renderMap(features) { const host = el("worldMap"); host.replaceChildren(); const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg"); svg.setAttribute("class", "oa-venus-map"); svg.setAttribute("viewBox", "0 0 360 180"); svg.setAttribute("preserveAspectRatio", "none"); svg.setAttribute("role", "img"); svg.setAttribute("aria-label", `${labels[state.body]}: ${features.length}`); const grid = document.createElementNS("http://www.w3.org/2000/svg", "g"); grid.setAttribute("class", "oa-venus-grid"); for (let lon = 0; lon <= 360; lon += 45) { const line = document.createElementNS("http://www.w3.org/2000/svg", "line"); line.setAttribute("x1", lon); line.setAttribute("x2", lon); line.setAttribute("y1", "0"); line.setAttribute("y2", "180"); grid.append(line); } for (let lat = -60; lat <= 60; lat += 30) { const line = document.createElementNS("http://www.w3.org/2000/svg", "line"); line.setAttribute("x1", "0"); line.setAttribute("x2", "360"); line.setAttribute("y1", String(90 - lat)); line.setAttribute("y2", String(90 - lat)); grid.append(line); } svg.append(grid); for (const feature of features.slice(0, 2600)) { const x = Math.max(0, Math.min(360, Number(feature.longitudeEast))); const y = Math.max(0, Math.min(180, 90 - Number(feature.latitude))); const point = document.createElementNS("http://www.w3.org/2000/svg", "g"); point.setAttribute("class", `oa-venus-point${feature.id === state.selectedId ? " is-selected" : ""}`); point.setAttribute("data-group", groupFor(feature)); point.setAttribute("tabindex", "0"); point.setAttribute("role", "button"); point.setAttribute("aria-label", `${feature.name}. ${feature.type || t.feature}`); point.setAttribute("transform", `translate(${x} ${y})`); const dot = document.createElementNS("http://www.w3.org/2000/svg", "circle"); dot.setAttribute("r", feature.id === state.selectedId ? "1.8" : "1.12"); const hit = document.createElementNS("http://www.w3.org/2000/svg", "circle"); hit.setAttribute("class", "oa-venus-hit"); hit.setAttribute("r", "4"); point.append(dot, hit); point.addEventListener("click", () => select(feature.id)); point.addEventListener("keydown", event => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); select(feature.id); } }); svg.append(point); } host.append(svg); }
  function renderLayers() { const host = el("worldLayers"); host.replaceChildren(); for (const [code, label] of groups) { const button = make("button", { className: `oa-venus-layer${state.active.has(code) ? " is-active" : ""}`, type: "button", text: t[label] }); button.setAttribute("aria-pressed", String(state.active.has(code))); button.addEventListener("click", () => { state.active.has(code) ? state.active.delete(code) : state.active.add(code); if (!state.active.size) state.active.add(code); render(); }); host.append(button); } }
  function renderDetail() { const host = el("worldDetail"); host.replaceChildren(); const feature = state.data?.features.find(item => item.id === state.selectedId); if (!feature) { host.append(make("p", { className: "oa-venus-detail__eyebrow", text: t.feature }), make("h2", { text: labels[state.body] }), make("p", { className: "oa-venus-origin", text: t.select })); return; } host.append(make("p", { className: "oa-venus-detail__eyebrow", text: `${t.feature} · ${feature.code || "—"}` }), make("h2", { text: feature.name }), make("p", { className: "oa-venus-detail__type", text: feature.type || "—" })); const facts = make("div", { className: "oa-venus-facts" }); [[t.diameter, feature.diameterKm == null ? "—" : `${nf.format(feature.diameterKm)} km`], [t.coordinates, `${nf.format(feature.latitude)}° · ${nf.format(feature.longitudeEast)}°E`], [t.approval, feature.approvalDate || feature.approval || "—"], [t.quad, feature.quad || "—"]].forEach(([label, value]) => { const item = document.createElement("div"); item.append(make("small", { text: label }), make("strong", { text: value })); facts.append(item); }); host.append(facts); if (feature.origin) host.append(make("p", { className: "oa-venus-origin", text: `${t.origin}: ${feature.origin}` })); const link = make("a", { className: "oa-venus-source-link", text: t.source }); link.href = safeUrl(feature.sourceUrl); link.target = "_blank"; link.rel = "noreferrer"; host.append(link); }
  function renderResults(features) { const host = el("worldResults"); host.replaceChildren(); if (!features.length) { host.append(make("div", { className: "oa-venus-notice", text: t.noResults })); return; } [...features].sort((a, b) => a.name.localeCompare(b.name, "en")).slice(0, 70).forEach(feature => { const button = make("button", { className: `oa-venus-result${feature.id === state.selectedId ? " is-selected" : ""}`, type: "button" }); const labels = document.createElement("span"); labels.append(make("strong", { text: feature.name }), make("small", { text: `${feature.type || t.feature} · ${nf.format(feature.latitude)}° / ${nf.format(feature.longitudeEast)}°E` })); button.append(labels, make("code", { text: feature.code || "—" })); button.addEventListener("click", () => select(feature.id)); host.append(button); }); }
  function render() { const features = visible(); el("worldCount").textContent = `${nf.format(state.data.featureCount)} ${t.count}`; el("worldMapMeta").textContent = `${nf.format(features.length)} ${t.visible}`; el("worldSnapshot").textContent = `${t.updated}: ${df.format(new Date(state.data.snapshotAt))}`; el("worldTitle").textContent = labels[state.body]; el("worldSourceLink").href = state.data.source.targetUrl; el("worldSourceLink").textContent = `${t.sourceLabel}: USGS ${labels[state.body]} ↗`; renderLayers(); renderMap(features); renderDetail(); renderResults(features); }
  function load(body) { state.body = body; state.data = null; state.selectedId = ""; syncUrl(); el("worldMap").replaceChildren(make("div", { className: "oa-venus-notice", text: t.loading })); el("worldResults").replaceChildren(); document.querySelectorAll("[data-world]").forEach(button => button.classList.toggle("is-active", button.dataset.world === body)); fetch(`${apiBase}/api/orbital/${endpoints[body]}`, { headers: { Accept: "application/json" } }).then(async r => { const data = await r.json(); const min = body === "moon" ? 7500 : 1500; if (!r.ok || !Array.isArray(data.features) || data.features.length < min) throw new Error(data.error || "Invalid snapshot"); return data; }).then(data => { state.data = data; render(); }).catch(() => { el("worldMap").replaceChildren(make("div", { className: "oa-venus-notice", text: t.unavailable })); el("worldResults").replaceChildren(make("div", { className: "oa-venus-notice", text: t.unavailable })); }); }
  el("worldSearch").placeholder = t.search; el("worldSearch").addEventListener("input", event => { state.query = event.target.value; if (state.data) render(); }); el("worldShare").textContent = t.share; el("worldShare").addEventListener("click", async () => { try { await navigator.clipboard.writeText(location.href); el("worldShare").textContent = t.copied; setTimeout(() => { el("worldShare").textContent = t.share; }, 1800); } catch { el("worldShare").textContent = location.href; } }); document.querySelectorAll("[data-world]").forEach(button => button.addEventListener("click", () => load(button.dataset.world))); load(state.body);
})();
